### ISSUE TITLE
outputModuleName should be moduleName

### ISSUE THREAD

**Issue by mattdarveniza** [fraserxu/gulp-html2js#10]
Maybe I'm missing something but it seems that `outputModuleName` has no effect in the html2js settings dict, and `moduleName` is the actual desired attribute. Should the docs be updated to reflect that?

**Comment by diego-vieira** [comment]
it seems that https://github.com/fraserxu/gulp-html2js/commit/ff00860d0dc12c50beed71cbe3e0a3515173df26 broke pretty much everything
