### ISSUE TITLE
Multiple Templates at Once

### ISSUE THREAD

**Issue by calebthebrewer** [fraserxu/gulp-html2js#7]
This is probably just me being dense, but I am having some issues getting multiple templates dropped into the cache at once. Instead, the resulting file contains multiple `app.run` blocks, each of which inject just one template into the cache. How can I get multiple templates done in one run block?

**Comment by Luddinus** [comment]
+1

**Comment by cfv1000** [comment]
Hello,
This would require a complete rewrite of the module, I believe. 
If you use this module without CONCAT, the result will be multiple JS files, and all of them require the app.run. If you want to obtain a single file, with a single app.run, you need to rewrite (or create a new plugin) which does not require concat. You can take example from CONCAT, and create something similar.

**Comment by cfv1000** [comment]
Sorry for the double post - see #14

**Comment by fraserxu** [comment]
Thanks for the great work to @cfv1000 , the update is pushed to v0.4.0

**Comment by diego-vieira** [comment]
looks like OP is not active on this thread anymore - plus it's almost 2 years old - close?
